// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ExerciseKind.
const (
	Chord      ExerciseKind = "chord"
	Interval   ExerciseKind = "interval"
	Melody     ExerciseKind = "melody"
	Rhythm     ExerciseKind = "rhythm"
	SingleNote ExerciseKind = "singleNote"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string       `json:"accessToken"`
	RefreshToken *string      `json:"refreshToken,omitempty"`
	User         UserResponse `json:"user"`
}

// DailyProgress defines model for DailyProgress.
type DailyProgress struct {
	// ByExercise Solved count per exercise kind, only for kinds practised today.
	ByExercise *map[string]int `json:"byExercise,omitempty"`
	Correct    int             `json:"correct"`

	// Date Calendar date in the server's APP_TIMEZONE.
	Date   openapi_types.Date `json:"date"`
	Solved int                `json:"solved"`
}

// EmailAuthRequest defines model for EmailAuthRequest.
type EmailAuthRequest struct {
	Code  string              `json:"code"`
	Email openapi_types.Email `json:"email"`
	Name  *string             `json:"name"`
}

// EmailCodeRequest defines model for EmailCodeRequest.
type EmailCodeRequest struct {
	Email openapi_types.Email `json:"email"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   string  `json:"error"`
	Message *string `json:"message,omitempty"`
}

// ExerciseKind The five exercise modules. Melody and rhythm are scored as a whole.
type ExerciseKind string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// PracticeRecordRequest defines model for PracticeRecordRequest.
type PracticeRecordRequest struct {
	Chosen  *string `json:"chosen"`
	Correct bool    `json:"correct"`

	// Exercise The five exercise modules. Melody and rhythm are scored as a whole.
	Exercise ExerciseKind `json:"exercise"`
	Expected *string      `json:"expected"`
}

// StudyPlan defines model for StudyPlan.
type StudyPlan struct {
	DailyGoal      int            `json:"dailyGoal"`
	FocusExercises []ExerciseKind `json:"focusExercises"`
	Today          DailyProgress  `json:"today"`
}

// StudyPlanUpdate defines model for StudyPlanUpdate.
type StudyPlanUpdate struct {
	DailyGoal      int             `json:"dailyGoal"`
	FocusExercises *[]ExerciseKind `json:"focusExercises,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	AvatarUrl *string             `json:"avatarUrl"`
	CreatedAt time.Time           `json:"createdAt"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Name      *string             `json:"name"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// RequestEmailCodeJSONRequestBody defines body for RequestEmailCode for application/json ContentType.
type RequestEmailCodeJSONRequestBody = EmailCodeRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = EmailAuthRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = EmailAuthRequest

// UpdateStudyPlanJSONRequestBody defines body for UpdateStudyPlan for application/json ContentType.
type UpdateStudyPlanJSONRequestBody = StudyPlanUpdate

// CreatePracticeRecordJSONRequestBody defines body for CreatePracticeRecord for application/json ContentType.
type CreatePracticeRecordJSONRequestBody = PracticeRecordRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Send an email verification code
	// (POST /auth/code)
	RequestEmailCode(c *gin.Context)
	// Login with email verification code
	// (POST /auth/login)
	Login(c *gin.Context)
	// Logout current user
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// Get current user
	// (GET /auth/me)
	GetMe(c *gin.Context)
	// Register or login with email verification code
	// (POST /auth/register)
	Register(c *gin.Context)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// Get the study plan and today's progress for the current user
	// (GET /me/plan)
	GetStudyPlan(c *gin.Context)
	// Create or replace the study plan for the current user
	// (PUT /me/plan)
	UpdateStudyPlan(c *gin.Context)
	// Record the result of one answered question
	// (POST /me/practice-records)
	CreatePracticeRecord(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// RequestEmailCode operation middleware
func (siw *ServerInterfaceWrapper) RequestEmailCode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RequestEmailCode(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetStudyPlan operation middleware
func (siw *ServerInterfaceWrapper) GetStudyPlan(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStudyPlan(c)
}

// UpdateStudyPlan operation middleware
func (siw *ServerInterfaceWrapper) UpdateStudyPlan(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateStudyPlan(c)
}

// CreatePracticeRecord operation middleware
func (siw *ServerInterfaceWrapper) CreatePracticeRecord(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePracticeRecord(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/code", wrapper.RequestEmailCode)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/me/plan", wrapper.GetStudyPlan)
	router.PUT(options.BaseURL+"/me/plan", wrapper.UpdateStudyPlan)
	router.POST(options.BaseURL+"/me/practice-records", wrapper.CreatePracticeRecord)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYS28bNxD+KwRbIBdFkh0nQHWq47qp2zgR/EDRJkYxXo60jHfJzZArexvovxfDXT32",
	"IclpbSOH3kSR/OabJ2f2i4xsmlmDxjs5+iIJXWaNw7B4DeoMP+foPK8iazya8BOyLNEReG3N4JOzhv9z",
	"UYwp8K/vCSdyJL8brKAH5a4bHBNZOquEyPl83pMKXUQ6YzA5YpmCKqHznryw9hRMUdFwT8fjwlqRgikW",
	"ZByzuTSQ+9iS/hvV01GpSeXt6iYDH+Y+Xt4dfZEZ2QzJ69KBEEXo3IW9wcDHFxnKkXSetJmyPoQTQhdv",
	"PpA7pF38Lx2u02fUz7kmttCHEqBXI3LVW8ix158wCm7+CXRSjMlOCZ1r63FdHN8hRbrUEZTSbBpIxrVT",
	"Fao2HqdIsmXHc5vMUInI5saLDElgBSputFE9YU1SiImlsHQiI4i8dqiEtwqKvuzgHVki/tktHXzgW2dx",
	"BAkaBSR4W2gjfIzCIc2QnjlxOB7/dXFyevzn+3fHLHFiKQUvRyVYr+0hF5TqItDwRAVQnV9R73LHcQo6",
	"KUNrmf51j0RWBd3wDtIs4dt7+y8OXr6SPZnC3Vs0Ux/L0aueTLVZW7XoI0uqA3HI/Fgt+5FN161QHu/A",
	"MZA2+BwmOsI6nb3hsCdNniRwzUc85diCalhtITDou9FUR1bhRlM9jIqdvDoJ1cpJmw1vd+Z6is7BFDv2",
	"mrIDRKfsKqF+00a1I/8iRjHRM1zlXWpVnqDri1NMrCoEGCUoLnycCiAULrKESoATIG5jmyBnBJo8ZRZO",
	"m2mC72yIag56mkHwVGyJ4zsNkLInS8A1viuVf0FIttVP58Hnru47e7PTOdW1LguNQ1GJ8AwjS2pzesXW",
	"lSV5R7h2laBraxMEE9JrrWxufYPWHRfuZRj5sq58ZcIsJG6vMOc+V8U4AdPWXfFb8MZCyJkU7nTKDn/J",
	"uZtqU672eh31dmKj3C00CVDaY+q+VvcKGIigCGuu/rtA6g9Yu/YuVGqxXOBvNdJltnhLvmVTbVS6S7da",
	"19BuXGbggS4puV8KEIJHdRiSoPZiPvc67Xw2l0V599OiVe1cnmu17QXayTYPzvwKtg27BvHLd2mp+jpw",
	"2+DcKWCUk/bFOTuz6qsQCIkf+tXq5wWjX3+/kFWvGapK2F2xi73Pym5Vm4ltV/vD8Ulopri9eR+LP2xO",
	"4hhIIJDwBNpoMxVrXTMjax9K7Prxw/GJ7MkZkith9/rD/pDNaDM0kGk5ki/6w/4L2ZMZ+DioNeB+ebBo",
	"UTJbVtgGveQWCifAuFskJ/aHB4EtiBkkWglQijNZOBsUQKMyq40XERhjvbhGkZed4UfDDxISN3MQhd7S",
	"9cV7biWtQcEkQq+5ANRO3GDmBST8EoIXINjr/Y9sAE6BYIwTJUeyeh2WHYYs4wCdf80v24PNH80OZl6P",
	"OA7j8MfaZLg/POjobFlXx3zmPXkwHG4SvEQarA2YfGX/h91XmgNhiOw8TYEKbvHRKAFGhPQQMyQ9qYwS",
	"PBFOl9GR2Kk26+FRt/3bsP2IBl/vru9l8OGDya/NjB3zJu+j8QyOiuOcxK32sfA8vrl/69zh3u4r7Ul3",
	"6dngkJLHvZxrc7/Vu7x/n6B+a6dTVMLmXrg8TLGTPEmK/6BSVYbl6EO9AH+4ml81NGapUU6Exgc/rKlY",
	"PjZT7NDuDfpTlI8YQI2JvxVARzXKj26oN7jRSoRT7Xz5DaM7FM4WJ/7P9W8m1xc+EZZEcs+8j8Moty0n",
	"ymHvMfOiMU52mPscaaYj5C6gJFw0VC8hRBRjdFMqluIgq+akTZqthqlHVG4lpEsv3hTMcxE+CopnTmTL",
	"iehJqkD4lLaiAka1mCx70qhRpLK8w7jl4FW378MXieac98Q1YrtnYYZqzahPWxLu6/yjMAZxvSDMEoiw",
	"GQrdXl/kV/VR5jmFrzJu82tRyql/xHmkoOj+UnSv0NhrtzElinDe8r1v0ocVRfYSocsTL+wkzFDljIZK",
	"BCasz7wEJh4LA26zZ4sgEQpnmNgsZU/0ZE6JHMkBZHow25Pzq/k/AQAA//8EcirD+hoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
