// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ExerciseKind.
const (
	Chord      ExerciseKind = "chord"
	Interval   ExerciseKind = "interval"
	Melody     ExerciseKind = "melody"
	Rhythm     ExerciseKind = "rhythm"
	SingleNote ExerciseKind = "singleNote"
)

// Achievement defines model for Achievement.
type Achievement struct {
	Achieved bool `json:"achieved"`

	// Id Stable id; the client maps it to a title and description.
	Id       string `json:"id"`
	Progress int    `json:"progress"`
	Target   int    `json:"target"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string       `json:"accessToken"`
	RefreshToken *string      `json:"refreshToken,omitempty"`
	User         UserResponse `json:"user"`
}

// DailyBucket defines model for DailyBucket.
type DailyBucket struct {
	Correct int                `json:"correct"`
	Date    openapi_types.Date `json:"date"`

	// Goal The daily goal that applied that day.
	Goal int `json:"goal"`

	// Met Solved reached the goal.
	Met    bool `json:"met"`
	Solved int  `json:"solved"`
}

// DailyHistory defines model for DailyHistory.
type DailyHistory struct {
	// CurrentStreak Consecutive days up to today (or yesterday) with any practice.
	CurrentStreak int           `json:"currentStreak"`
	Days          []DailyBucket `json:"days"`
	LongestStreak int           `json:"longestStreak"`
}

// DailyProgress defines model for DailyProgress.
type DailyProgress struct {
	// ByExercise Solved count per exercise kind, only for kinds practised today.
	ByExercise *map[string]int `json:"byExercise,omitempty"`
	Correct    int             `json:"correct"`

	// Date Calendar date in the server's APP_TIMEZONE.
	Date   openapi_types.Date `json:"date"`
	Solved int                `json:"solved"`
}

// EmailAuthRequest defines model for EmailAuthRequest.
type EmailAuthRequest struct {
	Code  string              `json:"code"`
	Email openapi_types.Email `json:"email"`
	Name  *string             `json:"name"`
}

// EmailCodeRequest defines model for EmailCodeRequest.
type EmailCodeRequest struct {
	Email openapi_types.Email `json:"email"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   string  `json:"error"`
	Message *string `json:"message,omitempty"`
}

// ExerciseKind The five exercise modules. Melody and rhythm are scored as a whole.
type ExerciseKind string

// ExerciseStats defines model for ExerciseStats.
type ExerciseStats struct {
	// Accuracy Fraction between 0 and 1; 0 when nothing was solved.
	Accuracy float64 `json:"accuracy"`
	Correct  int     `json:"correct"`
	Solved   int     `json:"solved"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// Level defines model for Level.
type Level struct {
	// Config The parameter set the exercise runs with.
	Config    *map[string]interface{} `json:"config,omitempty"`
	PassMark  float64                 `json:"passMark"`
	Position  int                     `json:"position"`
	Questions int                     `json:"questions"`
	Slug      string                  `json:"slug"`
	Title     LocalizedText           `json:"title"`
}

// LevelProgress defines model for LevelProgress.
type LevelProgress struct {
	// BestAccuracy Best fraction of correct answers across attempts, 0–1.
	BestAccuracy float64 `json:"bestAccuracy"`
	LevelId      string  `json:"levelId"`

	// Module The five exercise modules. Melody and rhythm are scored as a whole.
	Module ExerciseKind `json:"module"`
	Passed bool         `json:"passed"`
}

// LevelResultRequest defines model for LevelResultRequest.
type LevelResultRequest struct {
	Correct int `json:"correct"`

	// Module The five exercise modules. Melody and rhythm are scored as a whole.
	Module ExerciseKind `json:"module"`

	// PassMark Accuracy needed to pass, 0–1. The server decides, not the client.
	PassMark float64 `json:"passMark"`
	Total    int     `json:"total"`
}

// LevelSet defines model for LevelSet.
type LevelSet struct {
	Description *LocalizedText `json:"description,omitempty"`
	Levels      []Level        `json:"levels"`

	// Module The five exercise modules. Melody and rhythm are scored as a whole.
	Module ExerciseKind  `json:"module"`
	Slug   string        `json:"slug"`
	Title  LocalizedText `json:"title"`
}

// LocalizedText defines model for LocalizedText.
type LocalizedText struct {
	En string `json:"en"`
	Zh string `json:"zh"`
}

// Mistake defines model for Mistake.
type Mistake struct {
	Answer string `json:"answer"`

	// Exercise The five exercise modules. Melody and rhythm are scored as a whole.
	Exercise    ExerciseKind            `json:"exercise"`
	Id          openapi_types.UUID      `json:"id"`
	LastWrongAt time.Time               `json:"lastWrongAt"`
	Prompt      *map[string]interface{} `json:"prompt"`
	WrongCount  int                     `json:"wrongCount"`
}

// PracticeRecordRequest defines model for PracticeRecordRequest.
type PracticeRecordRequest struct {
	Chosen  *string `json:"chosen"`
	Correct bool    `json:"correct"`

	// Exercise The five exercise modules. Melody and rhythm are scored as a whole.
	Exercise ExerciseKind `json:"exercise"`
	Expected *string      `json:"expected"`

	// Prompt The question itself (notes, interval, chord type, rhythm pattern...).
	// Wrong answers carrying a prompt land in the mistake notebook, and a
	// later correct answer for the same prompt clears the entry.
	Prompt *map[string]interface{} `json:"prompt"`
}

// PracticeStats defines model for PracticeStats.
type PracticeStats struct {
	Accuracy float64 `json:"accuracy"`

	// Achievements Evaluated on read; the client owns the wording.
	Achievements []Achievement `json:"achievements"`

	// ByExercise Keyed by exercise kind; kinds never practised are absent.
	ByExercise map[string]ExerciseStats `json:"byExercise"`
	Correct    int                      `json:"correct"`

	// Daily One entry per calendar day, oldest first, gaps filled with zeros.
	Daily  []DailyProgress `json:"daily"`
	Solved int             `json:"solved"`

	// Streak Consecutive days ending today (or yesterday, when today has no
	// practice yet) with at least one answered question.
	Streak int `json:"streak"`
}

// StudyPlan defines model for StudyPlan.
type StudyPlan struct {
	DailyGoal      int            `json:"dailyGoal"`
	FocusExercises []ExerciseKind `json:"focusExercises"`
	Today          DailyProgress  `json:"today"`
}

// StudyPlanUpdate defines model for StudyPlanUpdate.
type StudyPlanUpdate struct {
	DailyGoal      int             `json:"dailyGoal"`
	FocusExercises *[]ExerciseKind `json:"focusExercises,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	AvatarUrl *string             `json:"avatarUrl"`
	CreatedAt time.Time           `json:"createdAt"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Name      *string             `json:"name"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListDailyHistoryParams defines parameters for ListDailyHistory.
type ListDailyHistoryParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// ListMistakesParams defines parameters for ListMistakes.
type ListMistakesParams struct {
	Exercise *ExerciseKind `form:"exercise,omitempty" json:"exercise,omitempty"`
}

// RequestEmailCodeJSONRequestBody defines body for RequestEmailCode for application/json ContentType.
type RequestEmailCodeJSONRequestBody = EmailCodeRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = EmailAuthRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = EmailAuthRequest

// RecordLevelResultJSONRequestBody defines body for RecordLevelResult for application/json ContentType.
type RecordLevelResultJSONRequestBody = LevelResultRequest

// UpdateStudyPlanJSONRequestBody defines body for UpdateStudyPlan for application/json ContentType.
type UpdateStudyPlanJSONRequestBody = StudyPlanUpdate

// CreatePracticeRecordJSONRequestBody defines body for CreatePracticeRecord for application/json ContentType.
type CreatePracticeRecordJSONRequestBody = PracticeRecordRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Send an email verification code
	// (POST /auth/code)
	RequestEmailCode(c *gin.Context)
	// Login with email verification code
	// (POST /auth/login)
	Login(c *gin.Context)
	// Logout current user
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// Get current user
	// (GET /auth/me)
	GetMe(c *gin.Context)
	// Register or login with email verification code
	// (POST /auth/register)
	Register(c *gin.Context)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// The question-set catalog
	// (GET /levels/sets)
	ListLevelSets(c *gin.Context)
	// Per-day practice history for the calendar
	// (GET /me/daily)
	ListDailyHistory(c *gin.Context, params ListDailyHistoryParams)
	// Question-set progress for the current user
	// (GET /me/levels)
	ListLevelProgress(c *gin.Context)
	// Record a finished question-set level attempt
	// (POST /me/levels/{id})
	RecordLevelResult(c *gin.Context, id string)
	// List the open mistakes in the notebook
	// (GET /me/mistakes)
	ListMistakes(c *gin.Context, params ListMistakesParams)
	// Remove a mistake from the notebook
	// (DELETE /me/mistakes/{id})
	ResolveMistake(c *gin.Context, id openapi_types.UUID)
	// Get the study plan and today's progress for the current user
	// (GET /me/plan)
	GetStudyPlan(c *gin.Context)
	// Create or replace the study plan for the current user
	// (PUT /me/plan)
	UpdateStudyPlan(c *gin.Context)
	// Record the result of one answered question
	// (POST /me/practice-records)
	CreatePracticeRecord(c *gin.Context)
	// Practice totals, per-exercise accuracy, and a daily trend
	// (GET /me/stats)
	GetPracticeStats(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// RequestEmailCode operation middleware
func (siw *ServerInterfaceWrapper) RequestEmailCode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RequestEmailCode(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// ListLevelSets operation middleware
func (siw *ServerInterfaceWrapper) ListLevelSets(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLevelSets(c)
}

// ListDailyHistory operation middleware
func (siw *ServerInterfaceWrapper) ListDailyHistory(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDailyHistoryParams

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameter("form", true, false, "days", c.Request.URL.Query(), &params.Days)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter days: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDailyHistory(c, params)
}

// ListLevelProgress operation middleware
func (siw *ServerInterfaceWrapper) ListLevelProgress(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLevelProgress(c)
}

// RecordLevelResult operation middleware
func (siw *ServerInterfaceWrapper) RecordLevelResult(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RecordLevelResult(c, id)
}

// ListMistakes operation middleware
func (siw *ServerInterfaceWrapper) ListMistakes(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMistakesParams

	// ------------- Optional query parameter "exercise" -------------

	err = runtime.BindQueryParameter("form", true, false, "exercise", c.Request.URL.Query(), &params.Exercise)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter exercise: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMistakes(c, params)
}

// ResolveMistake operation middleware
func (siw *ServerInterfaceWrapper) ResolveMistake(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResolveMistake(c, id)
}

// GetStudyPlan operation middleware
func (siw *ServerInterfaceWrapper) GetStudyPlan(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStudyPlan(c)
}

// UpdateStudyPlan operation middleware
func (siw *ServerInterfaceWrapper) UpdateStudyPlan(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateStudyPlan(c)
}

// CreatePracticeRecord operation middleware
func (siw *ServerInterfaceWrapper) CreatePracticeRecord(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePracticeRecord(c)
}

// GetPracticeStats operation middleware
func (siw *ServerInterfaceWrapper) GetPracticeStats(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPracticeStats(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/code", wrapper.RequestEmailCode)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/levels/sets", wrapper.ListLevelSets)
	router.GET(options.BaseURL+"/me/daily", wrapper.ListDailyHistory)
	router.GET(options.BaseURL+"/me/levels", wrapper.ListLevelProgress)
	router.POST(options.BaseURL+"/me/levels/:id", wrapper.RecordLevelResult)
	router.GET(options.BaseURL+"/me/mistakes", wrapper.ListMistakes)
	router.DELETE(options.BaseURL+"/me/mistakes/:id", wrapper.ResolveMistake)
	router.GET(options.BaseURL+"/me/plan", wrapper.GetStudyPlan)
	router.PUT(options.BaseURL+"/me/plan", wrapper.UpdateStudyPlan)
	router.POST(options.BaseURL+"/me/practice-records", wrapper.CreatePracticeRecord)
	router.GET(options.BaseURL+"/me/stats", wrapper.GetPracticeStats)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb727cNrZ/lQPdC7QFlPE4SVvcyZfr5LptbuPGGzsodutgQYtnRqwpUiWpcZTCwL7D",
	"vuE+yeKQ+jvD8chJbOTDfstY0uH5+zv/mD+TTBelVqicTRZ/JgZtqZVF/+M542/wjwqto1+ZVg6V/ycr",
	"Syky5oRWB79brehvNsuxYPSv/za4TBbJfx30pA/CU3twbIw2b5pDkpubmzThaDMjSiKWLOhMMM2hN2ly",
	"rvUJU3XDhn04Ps61hoKpumXGEjdvFatcro34gPzhWBmdSo+bL4nwUZYLXGPRcFEaXaJxItiPhYeeVVeX",
	"mCySS60lMkXCCP/38VFnjl1KBMGfgcsRMilQOShYaUE4cBoYOOEkAlMcBp/OkjTB96woJR2SoXKVqZO0",
	"PdU6I9SKDi2NXhm0dsCSUA5XaOipY2aFLvbsJk3IEMKQNL8R7wNa3YdpL/K77nB9+Ttm3pmOKpd3io5o",
	"K0Nrz/UVqgEHPesGlwZtvvuFyqLZZ+y3Foe2HkvlCaQjRmJi/B8Tsn5eZVcYsXmmjaH3ovrlzHnBl9oU",
	"zCWL8IeImVaayW3vOM8ROB0O9Bxczhx4v0cefnBWz3pyg4OLwOqGs2m5Rop2luWeAnq6AwoDb7X+5Qmu",
	"0YjUvJ92CmmECrzsVOtPwjpt6oheK2NQuTNnkF1ty/KCDJpVTqxJRbWFqqRwcZqzGr7WBmq0Dg1n9Tdw",
	"LVwOBC2lYZkTGcZ1RmToIOGwsPv8augTNx01Zgyr6bfUaoV2wP1eJdYUVmOhN8nsVOLpIMjHWrysj9+j",
	"yUSIP8a5IP0xeTp6K6KLmONkulIOSjSADVG4EoqnoJWsYamN/2kbNVtyMT320J7vSWGzYXImUXFmgB6D",
	"UN6BLZo1mq8sHJ2e/v385cnx317/ckwn7g25T3bwmDmOCyZkgL0uj2/iBfey9eh9+PjJ02+/o0Bh71+h",
	"Wrk8WXyXJoVQg19b7COdNCZEcPa/zc9ZpouhFsLrETqKFRv8HEmR4Zidw/k8TVQlJWWrZOFMhVukNrTW",
	"Hujl3amqF5rjTlV9HhGjfEUZGtUF29zQ42geKtBatsLIs82zPYno2U1A/SwUj+eBJSFdF3eF5pVEO4MT",
	"lJrXvjwwee3yAphBsJk2yIFZYHCda+kRD1VVEBdWqJXEX7T3anJ6s/Y4neXacI/XRDJJk0BwwG8vcsvv",
	"mWPORlN7ZVhWb4vyg8cGreAS3TWigrnn/fAZzOE6RwVKu1yoFVwzCyHkxtGsK3LBjiVVFZcBNG5FlMnB",
	"HkljnTAxw/2ETN5W5FjHXGXHTqyv9npp81nsxFe4RhnDFbUUq90oH2J2269KZliBDg1YdB5SOyczlbI+",
	"eUYRvGTWnjBzNa5vdpqn1FaEY2P28QggtNqRjqysVmMd9k786DAGa75q3pfEX+mMSaryz/G927YBHTpg",
	"vCU65Haghp22uiU7o3VHO0PlOVoHyzZe9BIalwSm7DUaCywz2lpgzmFROpvC/F//+OfhxHCRxNpLfjet",
	"BtjZ22ANwazxlHhTtKHxlqfuoO7bdKyrnbp+g7aS7pbk22FEIZQoCBDn0fr5owVtQ2Jsy5ZzUIjcF0ZA",
	"L7cmg/OulAGOmeBoU0LCQVM40axOu9BJ3Cbfhto7ZfeYF8hM8e6zWFM0Ev5OMdg45vRCPMBhpAT/OBO2",
	"SHOPgNKpu4WTRuKoikcEt2uSeGP8Id9fi3zIfUkQPfVEWMeuYi27R57omTjoM+6i8DAV6Ty7qvyoYYu8",
	"ZNb9arRaHbmthvqREwXuGH4UpduXE3fUtb06runcF9T8TJ2UdMpIW5WNqIzFiVngtOlU32CmDd+NZ7m2",
	"wQf2FOex8mjQ7H+s8fB9iZkL2L6Xg2nW2K5Q2mwLwlmUS/haaUf42JauKfjKFejAtK2CS8qKRs1ms29m",
	"F8qrusubGTOmphqTQeAJJNWgTUdZBOcn+MVLra9SX6CyCyUZVUnjJOy7Xt+HsgJbaplEZmyopZQz9eyC",
	"ioc9brbZKvQedFu/2frJhDp8QvJg/XBzG8aT4zWTFXPIQSswyMYzS32tgsjX2nChVpSvJgH4cKIagfFp",
	"E4wpTht0tDXc+Blr5HBZj4caz5pZhkLKyf1Eg7ordmmbhHzXsYaQkTrvtWr8xI9Wsn7KUaegJfdVoDDW",
	"pbBipYWlkBJ5GGp9QKPtZE2PZ0URXe/uklKK42mDOFRk/tgkLg0dXniSMwtKX6h2Jgc1unZU50Aisw60",
	"wibOkHcwEKLpE9q4kU+1VukE3IiCWNCduYrXp5KpSOFDxH5shrkFex9KsG/n87QvyA5jBedSZ5VtuZpe",
	"/WwC8qZFva7v6Bdb469WpC0uW/q3Kult2Y7zvmRV7RQ6JttoqbANumvmmHlr5LS8bJAw9S5lTTcX2z/d",
	"m1hdtUPAvdxW3ph34DZaHbWjwU70IeF3sdRIEGOEq8/ImG3zzAyao8rl/a8fWo7+/9fzpNnb+VLHP+25",
	"y50rw+ZPqKWOtGunL7vM/jqHv+rKwDEzgMyAM0woXz30G8iumF8kw9ePTl8mabJGYwPZw9l8Nic16hIV",
	"K0WySJ7M5rMnvtFyuRfrgFUuP2inxKW2kUXOkbwmpG3rmcfzp55bBmsmBQfGOUUyWN3UILzUQjnImKKe",
	"8hKhCsP5C4WqKtAwh8AyP963M3itZO2hl5jwOaklKCxcYemASUJ75vx2ssCAyBQCXhkvebJImpK1G/Im",
	"wQ/Quuea159vl7s5RL4Zexy5sf/DYMv+eP40lsY4deChBnk6n+86uKN0MFjW0yeP/2f/J5vLde/ZVVEw",
	"UyeL5AypzlTgwwPWaMSyUYq3hH87eIfUK6GG7jHW/Sv/+B4VPlxwTFL4/LOdP1opR3b39ByVI+LIyc9N",
	"qCmcvkJlP9a488P9n2zfGugs6w0S+JhkXF25W61Lz6c49Su9WlG5XjmwlV9yLysp608QqYHhZPHbGIB/",
	"e3fzbkNiOrXZZ3o7DEQMyaa5eTCW7kd0J5jcowNtXAjYcqAXI5bvXVE/4k4tGVwJqpx3u8Kb9o3/xPoX",
	"E+utTUAbkBPjPvdLpNtiIqyZ7jMuNhZZEXWfoVlToyYsBIbrDdEDCchyzK6CYGGyeWAxzBNWsVspr5dL",
	"kQkmgd5qDJijMBA+TkEbTg3gDE6rSymyRZg6MMekXhEzpdG8ytyFavQQBjYrn2J9v14gU/4ylUWE65yF",
	"sbpknCPZSF9ZkOIKZ9D2QESqQAtLows4KLCRI1bnvBLWtXNw+6n2mT7wPotdO9k2mX/XK3bDVMO52iNL",
	"GBT0GcxW4EE3q4jbTCFc+ssvvj6UOmMyNrAQKpOVHwf40YA3rtL9PZwLdcyynB6SIX+vOKUrtmJCWdfd",
	"TwpXna6ZBaGozs2QHqlngSbZ6EJd4lKb8LqFazQIxk9OkcOSSQmXLLvy94PIdRq49Xefdph0dDeJqvNm",
	"SWo9oFPxlfxRoX8Weqf2Bk9vTI5LVkmXLJ58f5j2De7TUYP7fWSS8e4eo3wkV8Rh/PPGtNbHURiL2AdI",
	"hadoHpEndBOhPPDZdWLtaKxz0n5VFPVS7/1+KFlYlGsMaNDABTT6BI5LocIEsB9nPgOXCwsGXWWUvVAd",
	"avgsk7Nu60r+qjiENeWtAHHa3558IJDYPerbNvx4CNkLJ9v12j0b/y9DMGovmvaW36qQOusf/Cn4zW0l",
	"EsHAYDe8I5qp/+6D2Y8pxoXOMLSnLsxDKH/+wiyy6n7g0mzDvyLFgvM3kDYsKezQoR6qNpvqg8FXgMFS",
	"KGHzwczZe6XnvA2NzgubddFuFGo92/aj7OtmHcX9jr/7czOrlnVIgVCjXzJs48lJe+akzDRYJU2s+0eT",
	"0k/OR5MAq105T4GqElW7pbMpFNo6yvaoSHOFICAO9ceX6WVkQA9qeihHu31st45b/tXhHEeJYZ6+iXR+",
	"6dEq8jPA3J6xccQxIjOIhp+wFEX+kQqmjyLEf9FgqywfqbKHmi5b3AEBCr1GYD0t6gCidimb/c+ujq1f",
	"Et0jDPeHRCG44jUQn21bzFn9le0w+YGmG3473rNCqLfJyY48nyZlFVFuWCiN9fv5c+zm/uqBE+ztlmVr",
	"5AOlfplA98Kvd0AbMFhKFtq2oSvcWt21XcCj0MjZ3SVeOGd8Y+aenCJ+LWeSaxxuo1dTb1hfKn3RJRFZ",
	"yfh6E/QyvpbvDGfbqyi7kHF8Z+UeY2h8UGyAuFoZXPnpYdd0EvvCOpE9SMvbnurvW9qUmq9H3T2U9sZC",
	"cwOp+a9gzqAvy/w5Zt2m983Jv5/IUMWqS3+1Jk0qI5NFcsBKcbA+TG7e3fw7AAD//z1iLAOMOgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
