// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ExerciseKind.
const (
	Chord      ExerciseKind = "chord"
	Interval   ExerciseKind = "interval"
	Melody     ExerciseKind = "melody"
	Rhythm     ExerciseKind = "rhythm"
	SingleNote ExerciseKind = "singleNote"
)

// Achievement defines model for Achievement.
type Achievement struct {
	Achieved bool `json:"achieved"`

	// Id Stable id; the client maps it to a title and description.
	Id       string `json:"id"`
	Progress int    `json:"progress"`
	Target   int    `json:"target"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string       `json:"accessToken"`
	RefreshToken *string      `json:"refreshToken,omitempty"`
	User         UserResponse `json:"user"`
}

// DailyBucket defines model for DailyBucket.
type DailyBucket struct {
	Correct int                `json:"correct"`
	Date    openapi_types.Date `json:"date"`

	// Goal The daily goal that applied that day.
	Goal int `json:"goal"`

	// Met Solved reached the goal.
	Met    bool `json:"met"`
	Solved int  `json:"solved"`
}

// DailyHistory defines model for DailyHistory.
type DailyHistory struct {
	// CurrentStreak Consecutive days up to today (or yesterday) with any practice.
	CurrentStreak int           `json:"currentStreak"`
	Days          []DailyBucket `json:"days"`
	LongestStreak int           `json:"longestStreak"`
}

// DailyProgress defines model for DailyProgress.
type DailyProgress struct {
	// ByExercise Solved count per exercise kind, only for kinds practised today.
	ByExercise *map[string]int `json:"byExercise,omitempty"`
	Correct    int             `json:"correct"`

	// Date Calendar date in the server's APP_TIMEZONE.
	Date   openapi_types.Date `json:"date"`
	Solved int                `json:"solved"`
}

// EmailAuthRequest defines model for EmailAuthRequest.
type EmailAuthRequest struct {
	Code  string              `json:"code"`
	Email openapi_types.Email `json:"email"`
	Name  *string             `json:"name"`
}

// EmailCodeRequest defines model for EmailCodeRequest.
type EmailCodeRequest struct {
	Email openapi_types.Email `json:"email"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   string  `json:"error"`
	Message *string `json:"message,omitempty"`
}

// ExerciseKind The five exercise modules. Melody and rhythm are scored as a whole.
type ExerciseKind string

// ExerciseStats defines model for ExerciseStats.
type ExerciseStats struct {
	// Accuracy Fraction between 0 and 1; 0 when nothing was solved.
	Accuracy float64 `json:"accuracy"`
	Correct  int     `json:"correct"`
	Solved   int     `json:"solved"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// LevelProgress defines model for LevelProgress.
type LevelProgress struct {
	// BestAccuracy Best fraction of correct answers across attempts, 0–1.
	BestAccuracy float64 `json:"bestAccuracy"`
	LevelId      string  `json:"levelId"`

	// Module The five exercise modules. Melody and rhythm are scored as a whole.
	Module ExerciseKind `json:"module"`
	Passed bool         `json:"passed"`
}

// LevelResultRequest defines model for LevelResultRequest.
type LevelResultRequest struct {
	Correct int `json:"correct"`

	// Module The five exercise modules. Melody and rhythm are scored as a whole.
	Module ExerciseKind `json:"module"`

	// PassMark Accuracy needed to pass, 0–1. The server decides, not the client.
	PassMark float64 `json:"passMark"`
	Total    int     `json:"total"`
}

// Mistake defines model for Mistake.
type Mistake struct {
	Answer string `json:"answer"`

	// Exercise The five exercise modules. Melody and rhythm are scored as a whole.
	Exercise    ExerciseKind            `json:"exercise"`
	Id          openapi_types.UUID      `json:"id"`
	LastWrongAt time.Time               `json:"lastWrongAt"`
	Prompt      *map[string]interface{} `json:"prompt"`
	WrongCount  int                     `json:"wrongCount"`
}

// PracticeRecordRequest defines model for PracticeRecordRequest.
type PracticeRecordRequest struct {
	Chosen  *string `json:"chosen"`
	Correct bool    `json:"correct"`

	// Exercise The five exercise modules. Melody and rhythm are scored as a whole.
	Exercise ExerciseKind `json:"exercise"`
	Expected *string      `json:"expected"`

	// Prompt The question itself (notes, interval, chord type, rhythm pattern...).
	// Wrong answers carrying a prompt land in the mistake notebook, and a
	// later correct answer for the same prompt clears the entry.
	Prompt *map[string]interface{} `json:"prompt"`
}

// PracticeStats defines model for PracticeStats.
type PracticeStats struct {
	Accuracy float64 `json:"accuracy"`

	// Achievements Evaluated on read; the client owns the wording.
	Achievements []Achievement `json:"achievements"`

	// ByExercise Keyed by exercise kind; kinds never practised are absent.
	ByExercise map[string]ExerciseStats `json:"byExercise"`
	Correct    int                      `json:"correct"`

	// Daily One entry per calendar day, oldest first, gaps filled with zeros.
	Daily  []DailyProgress `json:"daily"`
	Solved int             `json:"solved"`

	// Streak Consecutive days ending today (or yesterday, when today has no
	// practice yet) with at least one answered question.
	Streak int `json:"streak"`
}

// StudyPlan defines model for StudyPlan.
type StudyPlan struct {
	DailyGoal      int            `json:"dailyGoal"`
	FocusExercises []ExerciseKind `json:"focusExercises"`
	Today          DailyProgress  `json:"today"`
}

// StudyPlanUpdate defines model for StudyPlanUpdate.
type StudyPlanUpdate struct {
	DailyGoal      int             `json:"dailyGoal"`
	FocusExercises *[]ExerciseKind `json:"focusExercises,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	AvatarUrl *string             `json:"avatarUrl"`
	CreatedAt time.Time           `json:"createdAt"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Name      *string             `json:"name"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListDailyHistoryParams defines parameters for ListDailyHistory.
type ListDailyHistoryParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// ListMistakesParams defines parameters for ListMistakes.
type ListMistakesParams struct {
	Exercise *ExerciseKind `form:"exercise,omitempty" json:"exercise,omitempty"`
}

// RequestEmailCodeJSONRequestBody defines body for RequestEmailCode for application/json ContentType.
type RequestEmailCodeJSONRequestBody = EmailCodeRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = EmailAuthRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = EmailAuthRequest

// RecordLevelResultJSONRequestBody defines body for RecordLevelResult for application/json ContentType.
type RecordLevelResultJSONRequestBody = LevelResultRequest

// UpdateStudyPlanJSONRequestBody defines body for UpdateStudyPlan for application/json ContentType.
type UpdateStudyPlanJSONRequestBody = StudyPlanUpdate

// CreatePracticeRecordJSONRequestBody defines body for CreatePracticeRecord for application/json ContentType.
type CreatePracticeRecordJSONRequestBody = PracticeRecordRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Send an email verification code
	// (POST /auth/code)
	RequestEmailCode(c *gin.Context)
	// Login with email verification code
	// (POST /auth/login)
	Login(c *gin.Context)
	// Logout current user
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// Get current user
	// (GET /auth/me)
	GetMe(c *gin.Context)
	// Register or login with email verification code
	// (POST /auth/register)
	Register(c *gin.Context)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// Per-day practice history for the calendar
	// (GET /me/daily)
	ListDailyHistory(c *gin.Context, params ListDailyHistoryParams)
	// Question-set progress for the current user
	// (GET /me/levels)
	ListLevelProgress(c *gin.Context)
	// Record a finished question-set level attempt
	// (POST /me/levels/{id})
	RecordLevelResult(c *gin.Context, id string)
	// List the open mistakes in the notebook
	// (GET /me/mistakes)
	ListMistakes(c *gin.Context, params ListMistakesParams)
	// Remove a mistake from the notebook
	// (DELETE /me/mistakes/{id})
	ResolveMistake(c *gin.Context, id openapi_types.UUID)
	// Get the study plan and today's progress for the current user
	// (GET /me/plan)
	GetStudyPlan(c *gin.Context)
	// Create or replace the study plan for the current user
	// (PUT /me/plan)
	UpdateStudyPlan(c *gin.Context)
	// Record the result of one answered question
	// (POST /me/practice-records)
	CreatePracticeRecord(c *gin.Context)
	// Practice totals, per-exercise accuracy, and a daily trend
	// (GET /me/stats)
	GetPracticeStats(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// RequestEmailCode operation middleware
func (siw *ServerInterfaceWrapper) RequestEmailCode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RequestEmailCode(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// ListDailyHistory operation middleware
func (siw *ServerInterfaceWrapper) ListDailyHistory(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDailyHistoryParams

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameter("form", true, false, "days", c.Request.URL.Query(), &params.Days)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter days: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDailyHistory(c, params)
}

// ListLevelProgress operation middleware
func (siw *ServerInterfaceWrapper) ListLevelProgress(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLevelProgress(c)
}

// RecordLevelResult operation middleware
func (siw *ServerInterfaceWrapper) RecordLevelResult(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RecordLevelResult(c, id)
}

// ListMistakes operation middleware
func (siw *ServerInterfaceWrapper) ListMistakes(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMistakesParams

	// ------------- Optional query parameter "exercise" -------------

	err = runtime.BindQueryParameter("form", true, false, "exercise", c.Request.URL.Query(), &params.Exercise)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter exercise: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMistakes(c, params)
}

// ResolveMistake operation middleware
func (siw *ServerInterfaceWrapper) ResolveMistake(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResolveMistake(c, id)
}

// GetStudyPlan operation middleware
func (siw *ServerInterfaceWrapper) GetStudyPlan(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStudyPlan(c)
}

// UpdateStudyPlan operation middleware
func (siw *ServerInterfaceWrapper) UpdateStudyPlan(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateStudyPlan(c)
}

// CreatePracticeRecord operation middleware
func (siw *ServerInterfaceWrapper) CreatePracticeRecord(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePracticeRecord(c)
}

// GetPracticeStats operation middleware
func (siw *ServerInterfaceWrapper) GetPracticeStats(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPracticeStats(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/code", wrapper.RequestEmailCode)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/me/daily", wrapper.ListDailyHistory)
	router.GET(options.BaseURL+"/me/levels", wrapper.ListLevelProgress)
	router.POST(options.BaseURL+"/me/levels/:id", wrapper.RecordLevelResult)
	router.GET(options.BaseURL+"/me/mistakes", wrapper.ListMistakes)
	router.DELETE(options.BaseURL+"/me/mistakes/:id", wrapper.ResolveMistake)
	router.GET(options.BaseURL+"/me/plan", wrapper.GetStudyPlan)
	router.PUT(options.BaseURL+"/me/plan", wrapper.UpdateStudyPlan)
	router.POST(options.BaseURL+"/me/practice-records", wrapper.CreatePracticeRecord)
	router.GET(options.BaseURL+"/me/stats", wrapper.GetPracticeStats)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb624ct/V/lYP5/4EkwHi1sp0Elb9UdpXEjR2rloygjYyCGp7dYcQhJyRn5UkgoO/Q",
	"N+yTFIec+3K144sEf+g37XLm8Fx+5776I8l0UWqFytnk6I/EoC21sug/PGX8Nf5WoXX0KdPKofJ/srKU",
	"ImNOaHXwq9WKvrNZjgWjv/7f4Co5Sv7voCd9EE7twYkx2rxuLklubm7ShKPNjCiJWHJEd4JpLr1Jk3Ot",
	"XzJVN2zY++PjXGsomKpbZixx80axyuXaiN+R3x8ro1vpuHmTCB9nucANFg0XpdElGieC/Vg49Ky6usTk",
	"KLnUWiJTJIzw34+vOnPsUiII/gRcjpBJgcpBwUoLwoHTwMAJJxGY4jB4dZGkCb5jRSnpkgyVq0ydpO2t",
	"1hmh1nRpafTaoLUDloRyuEZDp46ZNbrY2U2akCGEIWl+Id4HtLoX017kt93l+vJXzDyYjiuXd4qOaCtD",
	"a8/1FaoBBz3rBlcGbb77gcqi2WfsNxaHth5L5QmkI0ZiYvyFCVk/rbIrjNg808bQc1H9cua84CttCuaS",
	"o/BFxExrzeQ2Os5zBE6XA52Dy5kDj3vk4QNn9aInN7i4CKxOwKblBsnbWZZ7CujpDigM0Gr9wzOg0YjU",
	"PJ92CmmECrzsVOsPwjpt6oheK2NQuTNnkF1ty/KMDJpVTmxIRbWFqiR3cZqzGr7UBmq0Dg1n9VdwLVwO",
	"FFpKwzInMozrjMjQRcJhYffhaoiJm44aM4bV9FlqtUY74H6vEmtyq7HQUzI7lXg6cPKxFi/rk3doMhH8",
	"j3EuSH9Mno6eiugiBpxMV8pBiQawIQpXQvEUtJI1rLTxH22jZksQ02OE9nzPcpuJyZlExZkBOgahPIAt",
	"mg2aLywcn57+8/z5y5N/vPrphG7c63IfDfCYOU4KJmQIe10en8YL7mXro/fhw0ePv/6GHIW9e4Fq7fLk",
	"6Js0KYQafNpiH+mmMSEKZ39uPi4yXQy1EB6P0FGsmPBzLEWGY3YOl8s0UZWUlK2SI2cq3CI10Vp7oZd3",
	"p6qeaY47VfVpRIzyFWVoVBdsc0PH0TxUoLVsjZGz6d2eRPTuxqF+FIrH88CKIl3nd4XmlUS7gJcoNa99",
	"eWDy2uUFMINgM22QA7PA4DrX0kc8VFVBXFih1hJ/0h7VBHqz8XE6y7XhPl4TySRNAsEBv73ILb9njjkb",
	"Te2VYVm9Lcp3PjZoBZforhEVLD3vh09gCdc5KlDa5UKt4ZpZCC439mZdEQQ7llRVXIagcWtEme3skTTW",
	"CRMz3A/I5G1FjnXMVXYMYn21F6XNa7EbX+AG5S0RH6073qn+p2gdrFob6BU0YgJT9hqNBZYZbS0w57Ao",
	"nU1h+Z9//ftwpgkksfacj6Xt4fbgMBaAApT3Fu1DB6G6llkbL7Qnmmx56i7q3k3Hutqp69doK+luCegd",
	"7gqhREFOtozWZB8s6EtmIiVQyzkoRO6TLdDDrcngvEuPwDETHG1K3jVoNGaa1WkXqtPb5JuovVN270eB",
	"zECimMZfCuvYVaxb8ACNxl8clDjvo9rQkHUKqCrf5WyRl8y6n41W62O3Vcs/cKLAHX1XUbrdRVdIoTtS",
	"aq+Oa7r3GdVdc5u0Thlpq7IRlbE4MQucNkXya8y04bthn2sb+rI9dUEsMg/6jA81Hr4rMXMhBOzlYJ41",
	"tpOul50ipXAW5Qq+VNqRG7VZMwWfNIEuTNsEXFLwNGqxWHy1uFBe1V14zZgxNaU3BoEnkJT+mmK2COAn",
	"L8VLra9SnxvZhZLMoZnEal9w+xKYFdhSyyQyY/3XqJypFxcq2QuzaZXSI+i2UrfFyYwSYEaMYf1cxW6H",
	"upMNkxVzyEEr6l/H4xJ9rYLI19pwodYU1mY1ccNhTqSJm9c8zQFt0NFWX/Uj1sjhsh73U0+aNkohhe6+",
	"maLCjl3aJm6/b0clZKQceKUanPiuLusbrDoFLbkvFoSxLoU1Ky2shJTIQz/9OxptZ2t63KZGdL27QEvJ",
	"j+fNAFCR+WNDgDQUl+EkZxaUvlDtOABqdO2UwIFEZh1ohY2fIe/CQPCmj6ggR5hqrdIJOPGCmNOduYrX",
	"p5KpbYfzxL5v5kgFexcy9dfUuXV5+zBWl6x0VtmWq/kTkGlAnlrU6/o9cbHVebcibXHZ0r9VSW/KdpLw",
	"Oatqp9Ax2UbzzO2gu2GOmTdGzsvLBimmvk9Z07Xk+wcLM6urdv6wl9vKG/M9uI1WR+1UohN9SPhtLDVS",
	"iDHC1WdkzLbHYgbNceXy/tN3LUd//fk8aVYGvtTxpz13uXNlWDoItdKRqv70eZfZX+Xwd10ZOGEGkBlw",
	"hgnlq4d++UGUhfOd1vDx49PnSZps0NhA9nCxXCxJjbpExUqRHCWPFsvFI1+Pu9yLdcAqlx+0A6pS28gM",
	"+VheU6Rt65mHy8eeWwYbJgUHxjl5Mljd1CC81EI5yJii1uMSoQpzwQuFqirQMIfAMj9ZtAt4pWTtQy8x",
	"4XNSS1BYuMLSAZMU7Znzi5ECQ0QmF/DKoN4zaUrWbr6UBBygdU81rz/dGmk6v7oZI45g7L8YLPgeLh/H",
	"0hinRi3UII+Xy10Xd5QOBntCeuXhn/a/Mt3reWRXRcFMnRwlZ0h1pgLvHrBBI1aNUrwl/NMBHVKvhRrC",
	"Y6z7F/74DhU+nK3OUvjyk90/2mZF1oZ0jsoRceSEcxNqCqevUNkPNe7ycP8r2wvLzrLeIIGPWcbVlbvV",
	"unQ+B9Qv9HpN5XrlwFZ+v7aqpKw/QqQmDCdHv4wD8C9vb95OJKZbm1WKt8NAxJBsmqXnWLrv0b3E5A4B",
	"NNlFbgHo2YjlO1fU97hTSwbXgirn3VB43T7xP1//bHy9tQloA3Km3+d+fn2bT4QJ9136xWSGHlH3GZoN",
	"NWrCQmC4nogeSECWY3YVBCvwoGt617FtOPW+l36B6wsNqTMmY52vUJmsfF/pe0yvUqX7XfKFOmFZTofE",
	"3q8Vp7jH1kwo67ode1jXXzMLQlHBlCEdqSeB5sro4kJd4kqb8LgFajzB+BEcclgxKeGSZVd+x51j57d+",
	"fx+pgV4I60b7dSrzDCvQobE+MlAWT36r0J+FIrzdQvdW47hilXTJ0aNvD9O+U3o86pS+jbTEb+8QLiO5",
	"ImDx541prZ+ghf7a3kNMPUXzgJDQjRbywGdX0rczlg6kfj9hd6LUbyD8dKuwKDdo/RioNJpXmYNGn8Bx",
	"JVQYJfVzsSfgcmHBoKuMshfqmiBIxz5c5azb8hBeFYewFtmFpvHa6SPNO6trHt+43TZvGX48zeqF8yq+",
	"B+P/rRkTPbAUUxrGe8tvpdrO+gd/CH5zW66lMDDYRe3wZmrkemf2/e44Yw5de+6CLrjyp8/wkdXaPef4",
	"Cb4iWcf5LfrEksIOAXVfSX4uBgNWgMFKKGHzwfDSo9Jz3rpGh8Jm77A7CrXItv1M9LrZa3C/U+y+boae",
	"sg4pEGr00+rtePKyvXNWZhrsJGYWkKOR20fno1kBq91dzglVJap23WNTKLR1lO1RkeYKQYE41B+fJ8rI",
	"gD6o6aEc7RqrXV9t4auLcxwlhsHsNNL56XmryE8Q5vbMHyPAiDSzDT9hu4b8AxVML0WI/6SpQ85HquxD",
	"TZct3iMCFHqDwHpaRhdxu5TNImFX6d9vG+4wDPeXRENwxWsgPtv+irP6C9vF5Htqk/2atWeFot6Ukx15",
	"Pk3KKqLcsJkY6/fT59jpIuSeE+ztlmUb5AOlfp6B7pnfE1BDbbCULLRtQyjcWt21XcCD0MjZ3SVeuGf8",
	"04s7AkX89x2zoHG4Hb2aesP6UumzLonISsbXm6BX8f1uZzjb/qZhV2Qc//jhDn1ofFFsErVeG1z7MVTX",
	"dBL7wjqR3UvL297qf99lU2q+HnQ/aGhX381PWZp/Z3AGfVnm7zGbNr1PR8h+IkMVqy79bzTSpDIyOUoO",
	"WCkONofJzdub/wYAAP//RYbseVA1AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
