/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health check */
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/code': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Send an email verification code
     * @description Always answers 204 for a valid address so the endpoint cannot be used to
     *     enumerate accounts. Only one code per address is kept alive at a time.
     */
    post: operations['requestEmailCode']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Register or login with email verification code */
    post: operations['register']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login with email verification code */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get current user */
    get: operations['getMe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout current user */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/plan': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the study plan and today's progress for the current user */
    get: operations['getStudyPlan']
    /** Create or replace the study plan for the current user */
    put: operations['updateStudyPlan']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/practice-records': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Record the result of one answered question */
    post: operations['createPracticeRecord']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/stats': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Practice totals, per-exercise accuracy, and a daily trend */
    get: operations['getPracticeStats']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/daily': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Per-day practice history for the calendar
     * @description One bucket per local day, oldest first, including days with no practice.
     *     Each day is judged against the goal that was in force then; days from
     *     before goals were recorded fall back to the current goal.
     */
    get: operations['listDailyHistory']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/levels': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Question-set progress for the current user
     * @description Levels themselves are product content defined by the client; this returns
     *     what the user has attempted and passed.
     */
    get: operations['listLevelProgress']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/levels/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Record a finished question-set level attempt */
    post: operations['recordLevelResult']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/mistakes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List the open mistakes in the notebook
     * @description Questions answered wrong and not answered correctly again yet.
     */
    get: operations['listMistakes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/mistakes/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove a mistake from the notebook */
    delete: operations['resolveMistake']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    HealthResponse: {
      /** @example ok */
      status: string
    }
    EmailAuthRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string
      /** @example 123456 */
      code: string
      /** @example Alice */
      name?: string | null
    }
    AuthResponse: {
      user: components['schemas']['UserResponse']
      accessToken: string
      refreshToken?: string
    }
    EmailCodeRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string
    }
    /**
     * @description The five exercise modules. Melody and rhythm are scored as a whole.
     * @enum {string}
     */
    ExerciseKind: 'singleNote' | 'interval' | 'chord' | 'melody' | 'rhythm'
    DailyProgress: {
      /**
       * Format: date
       * @description Calendar date in the server's APP_TIMEZONE.
       */
      date: string
      solved: number
      correct: number
      /** @description Solved count per exercise kind, only for kinds practised today. */
      byExercise?: {
        [key: string]: number
      }
    }
    StudyPlan: {
      dailyGoal: number
      focusExercises: components['schemas']['ExerciseKind'][]
      today: components['schemas']['DailyProgress']
    }
    StudyPlanUpdate: {
      dailyGoal: number
      focusExercises?: components['schemas']['ExerciseKind'][]
    }
    PracticeRecordRequest: {
      exercise: components['schemas']['ExerciseKind']
      correct: boolean
      chosen?: string | null
      expected?: string | null
      /**
       * @description The question itself (notes, interval, chord type, rhythm pattern...).
       *     Wrong answers carrying a prompt land in the mistake notebook, and a
       *     later correct answer for the same prompt clears the entry.
       */
      prompt?: {
        [key: string]: unknown
      } | null
    }
    DailyBucket: {
      /** Format: date */
      date: string
      solved: number
      correct: number
      /** @description The daily goal that applied that day. */
      goal: number
      /** @description Solved reached the goal. */
      met: boolean
    }
    DailyHistory: {
      days: components['schemas']['DailyBucket'][]
      /** @description Consecutive days up to today (or yesterday) with any practice. */
      currentStreak: number
      longestStreak: number
    }
    LevelProgress: {
      /** @example singleNote-1 */
      levelId: string
      module: components['schemas']['ExerciseKind']
      passed: boolean
      /**
       * Format: double
       * @description Best fraction of correct answers across attempts, 0–1.
       */
      bestAccuracy: number
    }
    LevelResultRequest: {
      module: components['schemas']['ExerciseKind']
      correct: number
      total: number
      /**
       * Format: double
       * @description Accuracy needed to pass, 0–1. The server decides, not the client.
       */
      passMark: number
    }
    Mistake: {
      /** Format: uuid */
      id: string
      exercise: components['schemas']['ExerciseKind']
      prompt?: {
        [key: string]: unknown
      } | null
      answer: string
      wrongCount: number
      /** Format: date-time */
      lastWrongAt: string
    }
    Achievement: {
      /**
       * @description Stable id; the client maps it to a title and description.
       * @example century
       */
      id: string
      progress: number
      target: number
      achieved: boolean
    }
    ExerciseStats: {
      solved: number
      correct: number
      /**
       * Format: double
       * @description Fraction between 0 and 1; 0 when nothing was solved.
       */
      accuracy: number
    }
    PracticeStats: {
      solved: number
      correct: number
      /** Format: double */
      accuracy: number
      /**
       * @description Consecutive days ending today (or yesterday, when today has no
       *     practice yet) with at least one answered question.
       */
      streak: number
      /** @description Evaluated on read; the client owns the wording. */
      achievements: components['schemas']['Achievement'][]
      /** @description Keyed by exercise kind; kinds never practised are absent. */
      byExercise: {
        [key: string]: components['schemas']['ExerciseStats']
      }
      /** @description One entry per calendar day, oldest first, gaps filled with zeros. */
      daily: components['schemas']['DailyProgress'][]
    }
    UserResponse: {
      /** Format: uuid */
      id: string
      /** Format: email */
      email: string
      name?: string | null
      avatarUrl?: string | null
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
    }
    ErrorResponse: {
      error: string
      message?: string
    }
  }
  responses: {
    /** @description Bad request */
    BadRequest: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorResponse']
      }
    }
    /** @description Too many requests */
    TooManyRequests: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorResponse']
      }
    }
    /** @description Unauthorized */
    Unauthorized: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorResponse']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Service is healthy */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  requestEmailCode: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailCodeRequest']
      }
    }
    responses: {
      /** @description Code sent */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequest']
      429: components['responses']['TooManyRequests']
    }
  }
  register: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailAuthRequest']
      }
    }
    responses: {
      /** @description Authenticated user with tokens */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailAuthRequest']
      }
    }
    responses: {
      /** @description Authenticated user with tokens */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  getMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Logged out successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
    }
  }
  getStudyPlan: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Study plan with today's progress */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StudyPlan']
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  updateStudyPlan: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StudyPlanUpdate']
      }
    }
    responses: {
      /** @description Saved study plan */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StudyPlan']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  createPracticeRecord: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PracticeRecordRequest']
      }
    }
    responses: {
      /** @description Record stored */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  getPracticeStats: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Aggregated practice statistics */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PracticeStats']
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  listDailyHistory: {
    parameters: {
      query?: {
        days?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Daily buckets and streaks */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DailyHistory']
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  listLevelProgress: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description One entry per attempted level */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LevelProgress'][]
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  recordLevelResult: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LevelResultRequest']
      }
    }
    responses: {
      /** @description Stored progress for this level */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LevelProgress']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  listMistakes: {
    parameters: {
      query?: {
        exercise?: components['schemas']['ExerciseKind']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Open mistakes, most recently missed first */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Mistake'][]
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  resolveMistake: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Mistake cleared */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      /** @description No such open mistake for this user */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
