/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health check */
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/code': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Send an email verification code
     * @description Always answers 204 for a valid address so the endpoint cannot be used to
     *     enumerate accounts. Only one code per address is kept alive at a time.
     */
    post: operations['requestEmailCode']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/email/check': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Whether an address already has an account
     * @description A deliberate exception to the rest of this surface. Signing in never says whether an address is registered — /auth/code answers 204 for any address, /auth/login answers the same way for an unknown address and a wrong password — but the sign-up screen asks the question out loud, so that someone who already has an account is sent to the sign-in screen instead of through a code they do not need. The answer is an oracle for "who has an account here", which is why it shares the code endpoint's throttle.
     */
    post: operations['checkEmail']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Register or login with email verification code */
    post: operations['register']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Login with a verification code or a password
     * @description Supply exactly one of `code` or `password`. A verification code signs in as before, registering the account on first use; a password only works once the account has one (see /me/password). Both answer identically, and neither tells the caller whether the address exists.
     */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/password/reset': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set a new password using an email verification code
     * @description For the reader who cannot sign in because the password is gone: the code stands in for the current password, which is exactly what a forgotten one is not. Everything else about a password is unchanged — the same length floor, one success per code, the same throttle. Signing in is part of the answer, since the code already proved the address. An address with no account gets one, the way a first code login does, so this cannot be used to ask whether an address is registered.
     */
    post: operations['resetPassword']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get current user */
    get: operations['getMe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout current user */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/name': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Set this account's display name
     * @description The word the account is called by. Sign-in providers supply one; an account that signed up with a verification code has none until it is set here. Trimmed before it is stored, and empty is refused rather than kept as a blank name — an account with no name has a null one, and the client draws its own placeholder for that.
     */
    put: operations['setMyName']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Set or replace this account's password
     * @description `currentPassword` is required once the account has one; a first password needs none, because the session that sets it came from a verification code, which already proved the address.
     */
    put: operations['setMyPassword']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/avatar': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the avatar this user uploaded */
    get: operations['getMyAvatar']
    put?: never
    /** Upload or replace this user's avatar */
    post: operations['putMyAvatar']
    /** Remove this user's uploaded avatar */
    delete: operations['deleteMyAvatar']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/plan': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the study plan and today's progress for the current user */
    get: operations['getStudyPlan']
    /** Create or replace the study plan for the current user */
    put: operations['updateStudyPlan']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/practice-records': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Record the result of one answered question */
    post: operations['createPracticeRecord']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/stats': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Practice totals, per-exercise accuracy, and a daily trend */
    get: operations['getPracticeStats']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/daily': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Per-day practice history for the calendar
     * @description One bucket per local day, oldest first, including days with no practice.
     *     Each day is judged against the goal that was in force then; days from
     *     before goals were recorded fall back to the current goal.
     */
    get: operations['listDailyHistory']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/collections': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The user's collection folders
     * @description Folders of levels. The default folder is created on first read with an
     *     empty name, which the client renders in the reader's language.
     */
    get: operations['listCollections']
    put?: never
    /** Create a collection folder */
    post: operations['createCollection']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/collections/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete a collection folder */
    delete: operations['deleteCollection']
    options?: never
    head?: never
    /** Rename a collection folder */
    patch: operations['renameCollection']
    trace?: never
  }
  '/me/collections/{id}/levels/{levelId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Put a level in a folder */
    put: operations['addCollectionItem']
    post?: never
    /** Take a level out of a folder */
    delete: operations['removeCollectionItem']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/levels/sets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The question-set catalog
     * @description Official sets with their levels, ordered. Public: the catalog is product
     *     content, and guests are meant to see what the ladder looks like. Progress
     *     comes from /me/levels.
     */
    get: operations['listLevelSets']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/levels': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Question-set progress for the current user
     * @description Levels themselves are product content defined by the client; this returns
     *     what the user has attempted and passed.
     */
    get: operations['listLevelProgress']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/levels/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Record a finished question-set level attempt */
    post: operations['recordLevelResult']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/mistakes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List the open mistakes in the notebook
     * @description Questions answered wrong and not answered correctly again yet.
     */
    get: operations['listMistakes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/mistakes/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove a mistake from the notebook */
    delete: operations['resolveMistake']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    HealthResponse: {
      /** @example ok */
      status: string
    }
    /** @description Exactly one of code or password. */
    EmailAuthRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string
      /** @example 123456 */
      code?: string
      /** @example correct horse battery staple */
      password?: string
      /** @example Alice */
      name?: string | null
    }
    AuthResponse: {
      user: components['schemas']['UserResponse']
      accessToken: string
      refreshToken?: string
    }
    EmailCodeRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string
    }
    EmailCheckResponse: {
      registered: boolean
    }
    SetNameRequest: {
      /**
       * @description Trimmed before it is stored; the trimmed value is what gets saved.
       * @example Alex
       */
      name: string
    }
    SetPasswordRequest: {
      /** @description Required when the account already has a password. */
      currentPassword?: string | null
      /**
       * @description At least 8 characters, at most 72 bytes (bcrypt's limit).
       * @example correct horse battery staple
       */
      newPassword: string
    }
    /** @description A new password for an address proven by a code, for someone who is not signed in. */
    ResetPasswordRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string
      /** @example 123456 */
      code: string
      /**
       * @description At least 8 characters, at most 72 bytes (bcrypt's limit).
       * @example correct horse battery staple
       */
      newPassword: string
    }
    /**
     * @description The five exercise modules. Melody and rhythm are scored as a whole.
     * @enum {string}
     */
    ExerciseKind: 'singleNote' | 'interval' | 'chord' | 'melody' | 'rhythm'
    DailyProgress: {
      /**
       * Format: date
       * @description Calendar date in the server's APP_TIMEZONE.
       */
      date: string
      solved: number
      correct: number
      /** @description Solved count per exercise kind, only for kinds practised today. */
      byExercise?: {
        [key: string]: number
      }
    }
    StudyPlan: {
      dailyGoal: number
      focusExercises: components['schemas']['ExerciseKind'][]
      today: components['schemas']['DailyProgress']
    }
    StudyPlanUpdate: {
      dailyGoal: number
      focusExercises?: components['schemas']['ExerciseKind'][]
    }
    PracticeRecordRequest: {
      exercise: components['schemas']['ExerciseKind']
      correct: boolean
      chosen?: string | null
      expected?: string | null
      /**
       * @description The question itself (notes, interval, chord type, rhythm pattern...).
       *     Wrong answers carrying a prompt land in the mistake notebook, and a
       *     later correct answer for the same prompt clears the entry.
       */
      prompt?: {
        [key: string]: unknown
      } | null
    }
    DailyBucket: {
      /** Format: date */
      date: string
      solved: number
      correct: number
      /** @description The daily goal that applied that day. */
      goal: number
      /** @description Solved reached the goal. */
      met: boolean
    }
    DailyHistory: {
      days: components['schemas']['DailyBucket'][]
      /** @description Consecutive days up to today (or yesterday) with any practice. */
      currentStreak: number
      longestStreak: number
    }
    Collection: {
      /** Format: uuid */
      id: string
      /** @description Empty for the default folder, which the client names. */
      name: string
      isDefault: boolean
      /** @description Level slugs in this folder. */
      levels: string[]
    }
    CollectionRequest: {
      name: string
    }
    LocalizedText: {
      zh: string
      en: string
    }
    Level: {
      /** @example singleNote-1 */
      slug: string
      position: number
      title: components['schemas']['LocalizedText']
      questions: number
      /** Format: double */
      passMark: number
      /** @description The parameter set the exercise runs with. */
      config?: {
        [key: string]: unknown
      }
    }
    LevelSet: {
      slug: string
      module: components['schemas']['ExerciseKind']
      title: components['schemas']['LocalizedText']
      description?: components['schemas']['LocalizedText']
      levels: components['schemas']['Level'][]
    }
    LevelProgress: {
      /** @example singleNote-1 */
      levelId: string
      module: components['schemas']['ExerciseKind']
      passed: boolean
      /**
       * Format: double
       * @description Best fraction of correct answers across attempts, 0–1.
       */
      bestAccuracy: number
    }
    LevelResultRequest: {
      module: components['schemas']['ExerciseKind']
      correct: number
      total: number
      /**
       * Format: double
       * @description Accuracy needed to pass, 0–1. The server decides, not the client.
       */
      passMark: number
    }
    Mistake: {
      /** Format: uuid */
      id: string
      exercise: components['schemas']['ExerciseKind']
      prompt?: {
        [key: string]: unknown
      } | null
      answer: string
      wrongCount: number
      /** Format: date-time */
      lastWrongAt: string
    }
    ExerciseStats: {
      solved: number
      correct: number
      /**
       * Format: double
       * @description Fraction between 0 and 1; 0 when nothing was solved.
       */
      accuracy: number
    }
    PracticeStats: {
      solved: number
      correct: number
      /** Format: double */
      accuracy: number
      /**
       * @description Consecutive days ending today (or yesterday, when today has no
       *     practice yet) with at least one answered question.
       */
      streak: number
      /** @description Keyed by exercise kind; kinds never practised are absent. */
      byExercise: {
        [key: string]: components['schemas']['ExerciseStats']
      }
      /** @description One entry per calendar day, oldest first, gaps filled with zeros. */
      daily: components['schemas']['DailyProgress'][]
    }
    UserResponse: {
      /** Format: uuid */
      id: string
      /** Format: email */
      email: string
      name?: string | null
      avatarUrl?: string | null
      /** @description Whether this account can also sign in with a password. The client uses it to offer setting one, and to choose which field to show first. */
      hasPassword: boolean
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
    }
    ErrorResponse: {
      error: string
      message?: string
    }
  }
  responses: {
    /** @description Bad request */
    BadRequest: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorResponse']
      }
    }
    /** @description Too many requests */
    TooManyRequests: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorResponse']
      }
    }
    /** @description Unauthorized */
    Unauthorized: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorResponse']
      }
    }
  }
  parameters: {
    CollectionId: string
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Service is healthy */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  requestEmailCode: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailCodeRequest']
      }
    }
    responses: {
      /** @description Code sent */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequest']
      429: components['responses']['TooManyRequests']
    }
  }
  checkEmail: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailCodeRequest']
      }
    }
    responses: {
      /** @description Whether the address has an account */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EmailCheckResponse']
        }
      }
      400: components['responses']['BadRequest']
      429: components['responses']['TooManyRequests']
    }
  }
  register: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailAuthRequest']
      }
    }
    responses: {
      /** @description Authenticated user with tokens */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailAuthRequest']
      }
    }
    responses: {
      /** @description Authenticated user with tokens */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      429: components['responses']['TooManyRequests']
    }
  }
  resetPassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordRequest']
      }
    }
    responses: {
      /** @description Authenticated user with tokens */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      429: components['responses']['TooManyRequests']
    }
  }
  getMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Logged out successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
    }
  }
  setMyName: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetNameRequest']
      }
    }
    responses: {
      /** @description The account after the change */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  setMyPassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetPasswordRequest']
      }
    }
    responses: {
      /** @description Password stored */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      /** @description The current password is wrong */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getMyAvatar: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The uploaded picture */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'image/png': string
          'image/jpeg': string
        }
      }
      401: components['responses']['Unauthorized']
      /** @description This user has not uploaded one */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  putMyAvatar: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string
        }
      }
    }
    responses: {
      /** @description The user, with the new avatar URL */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      /** @description The picture is larger than the limit */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  deleteMyAvatar: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Removed; the account falls back to its provider picture or none */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
    }
  }
  getStudyPlan: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Study plan with today's progress */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StudyPlan']
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  updateStudyPlan: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StudyPlanUpdate']
      }
    }
    responses: {
      /** @description Saved study plan */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StudyPlan']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  createPracticeRecord: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PracticeRecordRequest']
      }
    }
    responses: {
      /** @description Record stored */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  getPracticeStats: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Aggregated practice statistics */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PracticeStats']
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  listDailyHistory: {
    parameters: {
      query?: {
        days?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Daily buckets and streaks */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DailyHistory']
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  listCollections: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Collections with the level slugs in each */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Collection'][]
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  createCollection: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CollectionRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  deleteCollection: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['CollectionId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      /** @description No such folder, or the default folder */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  renameCollection: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['CollectionId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CollectionRequest']
      }
    }
    responses: {
      /** @description Renamed */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      /** @description No such folder, or the default folder (which has no name) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  addCollectionItem: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['CollectionId']
        levelId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Added */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      /** @description No such folder for this user */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  removeCollectionItem: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['CollectionId']
        levelId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      /** @description No such folder for this user */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  listLevelSets: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Level sets */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LevelSet'][]
        }
      }
    }
  }
  listLevelProgress: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description One entry per attempted level */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LevelProgress'][]
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  recordLevelResult: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LevelResultRequest']
      }
    }
    responses: {
      /** @description Stored progress for this level */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LevelProgress']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  listMistakes: {
    parameters: {
      query?: {
        exercise?: components['schemas']['ExerciseKind']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Open mistakes, most recently missed first */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Mistake'][]
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  resolveMistake: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Mistake cleared */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      /** @description No such open mistake for this user */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
